server:
  port: 8081

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: solverequations@gmail.com
    password: exykafucbxmxycet
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  application:
    name: business-logic

  data:
    mongodb:
      uri: mongodb+srv://program_creator:posgrest1132@cluster0.isxtblr.mongodb.net/LinearSystem?retryWrites=true&w=majority
      database: LinearSystem

  datasource:
    url: jdbc:postgresql://localhost:5432/solequat
    username: postgres
    password: this1pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


routes:
  uris:
    route1: http://localhost:8765/worker/api/v1/equation
    route2: http://localhost:8765/worker/api/v1/equation/
    route3: http://localhost:8765/worker/api/v1/equations/
    route4: http://localhost:8765/worker/api/v1/result/
    route5: http://localhost:8765/worker/api/v1/vector/
    route6: http://localhost:8765/worker/api/v1/matrix/
